version: "3"
services:
  scrape:
    image: openstates/openstates
    environment:
    - BILLY_MONGO_HOST=database
    - MYSQL_HOST=mysql
    - DATABASE_URL=postgis://openstates:openstates@postgres/openstates
    - NEW_YORK_API_KEY
    - INDIANA_API_KEY
    - PUPA_ARGS
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - database
    - postgres
    entrypoint: /opt/openstates/openstates/pupa-scrape.sh
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=openstates
      - POSTGRES_PASSWORD=openstates
  openstates.org:
    image: openstates/openstates.org
    command: python manage.py runserver 0.0.0.0:8000
    environment:
    - MONGO_HOST=database
    ports:
    - "8000:8000"
    depends_on:
    - database
  database:
    image: mongo
    ports:
    - "27017:27017"
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=capublic
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  ca-download:
    image: openstates/openstates
    entrypoint: /opt/openstates/openstates/openstates/ca/download.sh
    environment:
    - MYSQL_HOST=mysql
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - mysql
  dbinit:
    image: openstates/openstates
    environment:
      - DATABASE_URL=postgis://openstates:openstates@postgres/openstates
    depends_on:
      - postgres
    volumes:
    - .:/opt/openstates/openstates/
    entrypoint: /opt/openstates/openstates/dbinit.sh
    #entrypoint: /opt/openstates/venv-pupa/bin/pupa dbinit us
